### ISSUE TITLE
Strange sentences in the parsed files for task 1

### ISSUE THREAD

**Issue by AMR-KELEG** [adobe-research/deft_corpus#22]
On working on the first task, I have noticed that some sentences are composed of less than 5 number of words.
After checking the parsing script, I couldn't really understand your idea of splitting the conll file into sentences using these regexps.
https://github.com/adobe-research/deft_corpus/blob/a4667bbce1af2b6a276d94f1e98bcb1bb5fbed4e/task1_converter.py#L40

One of the strange sentences is line 45 in the parsed `t7_government_1_404.deft` file:
`" 1993 . 7073 ."	"0"`

From the task's point of view, these sentences aren't definitions. But I am not sure whether this was done on purpose or not.

Thanks a lot.

**Comment by sashaspala** [comment]
Hi,

The regex is just looking for what we assumed would be "valid" sentences - in some cases there were parsing issues in the text, typically surrounding citations or equations from certain textbooks that would contain only a single '.' as a "sentence". 

We've just completed combing through most of the corpus to manually fix a lot of the tokenization errors that have been the source of quite a few problems. I believe this should fix most of these weird cases you're seeing in the task 1 format, but I'll go back and double check. The new data (with tokenization errors fixed) will be posted tomorrow.

**Comment by AMR-KELEG** [comment]
Ok, thanks @sashaspala for your efforts.

**Comment by sashaspala** [comment]
Alright so I misspoke yesterday - that regex is actually just checking to make sure that we don't include the sentence id numbers as independent sentences. Unfortunately there are a few sentences in the dataset that are simply just a year and a period (like what you saw before) - these are typically part or all of a citation for a previous sentence. Many have gone away with the new tokenization and are now part of the whole citation instead of a separate sentence, but there may still be some that are either missing or dangling from a citation that didn't in fact make it into the original text. I've separated these from the new sentence id cases so you should only now be seeing sentences with the year, rather than the year + the following sentence's id.
